### ISSUE TITLE
Keyerror:experiment

### ISSUE THREAD

**Issue by gk7279** [pepkit/geofetch#7] opened 2018-08-20 16:26 UTC
SRP: SRP087641
Parsing SRA file to download SRR records
Traceback (most recent call last):
  File "./geofetch.py", line 750, in <module>
    main(sys.argv[1:])
  File "./geofetch.py", line 543, in main
    experiment = line["Experiment"]
KeyError: 'Experiment'

**Comment by vreuter** [comment] 2018-08-20 16:34
@gk7279 can you post the command used?

**Comment by nsheff** [comment] 2018-08-20 21:11
I could reproduce this with: 

```
python geofetch.py -i GSE86881
```

**Comment by nsheff** [comment] 2018-08-20 21:17
The metadata provided from SRA is bad:

This URL is supposed to give some information, but it provides a file that says "Error: The server encountered an error while executing a command". Useful.

 http://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?save=efetch&db=sra&rettype=runinfo&term=SRP087641

**Comment by nsheff** [comment] 2018-08-20 21:31
This is actually a problem with SRA, looks like. I've confirmed it's a problem with other accessions as well. I've sent them a message:

> 
> I used to use A URL of this form to get the SRA run info metadata for a run:
> 
> https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?save=efetch&db=sra&rettype=runinfo&term=SRP087641
> 
> This is now returning a csv with the message:
> Error: The server encountered an error while executing a command
> 
> 
> If I take out the "rettype" parameter by doing this:
> 
> https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?save=efetch&db=sra&term=SRP087641
> 
> Then it works as expected, yielding an XML metadata for the experiment.
> 
> Did something change in the API or is this a server error?

**Comment by nsheff** [comment] 2018-08-22 17:15
@gk7279 I've gone back and forth with SRA and apparently the server problem that caused this is now fixed. My tests are working now. Try it again and it should work now.

**Closed by nsheff** 2018-08-22 17:15 UTC
